site_name: MetaSnek API

theme:
    name: readthedocs

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
              options:
                  show_source: false
                  show_root_heading: false

nav:
  - metasnek API: index.md
